text_to_mp3/urls.py
from django.urls import path, re_path
from . import views

app_name = 'text_to_mp3'

urlpatterns = [
    path('', views.home, name='home'),
    path('convert_input_text', views.convert_input_text, name='convert_input_text'),
    path('convert_file_content', views.convert_file_content, name='convert_file_content'),
    re_path(r'^(?P<task_id>[\w-]+)/$', views.get_conversion_progress, name='task_status'),
    re_path(r'^abort_task/(?P<task_id>[\w-]+)/$', views.abort_task, name='abort_task'),
    path('download_audio', views.download_audio, name='download_audio'),

]

text_to_speech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('text_to_mp3.urls', namespace='text_to_mp3')),
    re_path(r'^celery-progress/', include('celery_progress.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <title>Text To Speech</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <script src="{% static 'jquery-3.7.0.min.js' %}"></script>
</head>
<body>
    <main class="main_wrapper">
        <div class="heading-wrapper">
            <div class="bg-colored-heading-wrapper">
                <header>
                    <div class="span1">
                        <img src="{% static 'images/logo.png' %}" alt="">
                        <span>Text to Speech</span>
                    </div>
                <div class="span2">
                    <div class="mail-div"><span class="material-symbols-outlined mail-icon"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M140-160q-24 0-42-18t-18-42v-520q0-24 18-42t42-18h680q24 0 42 18t18 42v520q0 24-18 42t-42 18H140Zm340-302L140-685v465h680v-465L480-462Zm0-60 336-218H145l335 218ZM140-685v-55 520-465Z"/></svg></span><a class="mail-text" target="_blank" href="mailto:winifredigboama@gmail.com">Connect with me</a></div>
                    <div class="github-div"><svg class="github-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg><a class="github-text" target="_blank" href="https://github.com/Winnie-Fred">Find me on Github</a></div>
                </div>
                </header>
                
            </div>
            <div id="notification"></div>
            <div class="progress-bar"></div>
            <div class="pageHeading">
                <div id="return-div-wrapper"></div>
            </div>
        </div>
        <div id="spaceBetweenHeadingAndContent"></div>

        <div class="main-content-wrapper">
            {% block main_content %}
            {% endblock main_content %}
        </div>
        <div class="dynamic-content-wrapper">
            {% block dynamic_content %}
            {% endblock dynamic_content %}
        </div>
        <div class="config-wrapper-row">
            <div class="config-wrapper">
                <div class="config">
                    <h2 class="settings-text">Settings</h2>
                    <div id="selectWrapper" class="settings">
                        <div class="settings-lang">
                            <div class="choose_lang_form">
                                <label style="color: #1D262E; font-weight: 500; font-size: 16px; padding-bottom: 10px;" for="selectLangList">Choose the language the text is in</label>        
                                <select id="selectLangList" name="{{ choose_lang_form.select_lang.name }}">                    
                                    {% for value, label in choose_lang_form.select_lang.field.choices %}
                                    <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>  
                            </div>
                        </div>
                        <div class="settings-accent">
                            <div class="voice_accent_form">
                                <label style="color: #1D262E; font-weight: 500; font-size: 16px; padding-bottom: 10px;" for="selectVoiceAccentList">Choose an accent to read the text with</label>        
                                <select id="selectVoiceAccentList">          
                                    {% for value, label in voice_accent_form.select_voice_accent.field.choices %}
                                    <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>  
    <script src="{% static 'index.js' %}"></script>  
</body>
</html>

templates/conversion_in_progress.html
{% load static %}

{% block dynamic_content %}   
    <div class="div-wrapper-for-loaded-content">           
        <div class="main-container">
            <div class="progress-container">
                <div class="progress">
                    <div class="progress-done">0%</div>
                </div>
                <div class="progress-description">Converting...</div>
            </div>
            <div class="extra-progress-description">Please wait for the process to complete</div>
            <button class="abort-button">Abort</button>
        </div>            
    </div>            
{% endblock dynamic_content %}

templates/conversion_successful.html
{% load static %}

{% block dynamic_content %}    
    <div class="div-wrapper-for-loaded-content">
        <div id="loadedContent" class="animate-bottom">        
            <div class="main-container">
                <div class="check-container">
                    <div class="check-background">
                        <svg viewBox="0 0 65 51" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 25L27.3077 44L58.5 7" stroke="white" stroke-width="13" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                    </div>
                    <div class="check-shadow"></div>
                </div>
            </div>
            <div class="speak play">
                <div><a class="open-modal" id="speak" href="#modal">Speak</a></div>        
            </div>

            {% comment %} Modal {% endcomment %}
            <div id="modal">
                <div class="modal-content">
                    <a id="back-button" href="#" title="Close Audio Player" class="close"><svg id="closeAudioPlayerIcon" style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M443.6,387.1L312.4,255.4l131.5-130c5.4-5.4,5.4-14.2,0-19.6l-37.4-37.6c-2.6-2.6-6.1-4-9.8-4c-3.7,0-7.2,1.5-9.8,4  L256,197.8L124.9,68.3c-2.6-2.6-6.1-4-9.8-4c-3.7,0-7.2,1.5-9.8,4L68,105.9c-5.4,5.4-5.4,14.2,0,19.6l131.5,130L68.4,387.1  c-2.6,2.6-4.1,6.1-4.1,9.8c0,3.7,1.4,7.2,4.1,9.8l37.4,37.6c2.7,2.7,6.2,4.1,9.8,4.1c3.5,0,7.1-1.3,9.8-4.1L256,313.1l130.7,131.1  c2.7,2.7,6.2,4.1,9.8,4.1c3.5,0,7.1-1.3,9.8-4.1l37.4-37.6c2.6-2.6,4.1-6.1,4.1-9.8C447.7,393.2,446.2,389.7,443.6,387.1z"></path></svg>Close</a>                   
                    <div class="mediaplayerwrapper" id="mediaPlayerWrapper">
                        <div class="mediaplayer" id="mediaPlayer">
                        
                            <audio id="audioPlayer" src=""></audio>
                        
                            <div class="discarea">
                                <div class="disc">
                                </div>
                                <div class="stylus">
                                    <div class="pivot"></div>
                                    <div class="arm"></div>
                                    <div class="head"></div>
                                </div>
                            </div>
                            <div class="controls">
                                <span class="title" id="audioTitleLabel">{{ file_name }}</span>
                                <div class="buttons">                    
                                    <button id="playState" class="playstate">
                                        <svg class="fa-solid fa-play" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M73 39c-14.8-9.1-33.4-9.4-48.5-.9S0 62.6 0 80V432c0 17.4 9.4 33.4 24.5 41.9s33.7 8.1 48.5-.9L361 297c14.3-8.7 23-24.2 23-41s-8.7-32.2-23-41L73 39z"/></svg>
                                        <svg class="fa-solid fa-pause" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M48 64C21.5 64 0 85.5 0 112V400c0 26.5 21.5 48 48 48H80c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48H48zm192 0c-26.5 0-48 21.5-48 48V400c0 26.5 21.5 48 48 48h32c26.5 0 48-21.5 48-48V112c0-26.5-21.5-48-48-48H240z"/></svg>
                                    </button>
                                    <button id="stopItem" class="stop">
                                        <svg class="fa-solid fa-stop"xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M0 128C0 92.7 28.7 64 64 64H320c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg>
                                    </button>                    
                                </div>
                                <div class="subControls">
                                    <span class="duration" id="currentDuration">00:00</span>
                                    <svg class="fa-solid fa-volume-high" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M533.6 32.5C598.5 85.3 640 165.8 640 256s-41.5 170.8-106.4 223.5c-10.3 8.4-25.4 6.8-33.8-3.5s-6.8-25.4 3.5-33.8C557.5 398.2 592 331.2 592 256s-34.5-142.2-88.7-186.3c-10.3-8.4-11.8-23.5-3.5-33.8s23.5-11.8 33.8-3.5zM473.1 107c43.2 35.2 70.9 88.9 70.9 149s-27.7 113.8-70.9 149c-10.3 8.4-25.4 6.8-33.8-3.5s-6.8-25.4 3.5-33.8C475.3 341.3 496 301.1 496 256s-20.7-85.3-53.2-111.8c-10.3-8.4-11.8-23.5-3.5-33.8s23.5-11.8 33.8-3.5zm-60.5 74.5C434.1 199.1 448 225.9 448 256s-13.9 56.9-35.4 74.5c-10.3 8.4-25.4 6.8-33.8-3.5s-6.8-25.4 3.5-33.8C393.1 284.4 400 271 400 256s-6.9-28.4-17.7-37.3c-10.3-8.4-11.8-23.5-3.5-33.8s23.5-11.8 33.8-3.5zM301.1 34.8C312.6 40 320 51.4 320 64V448c0 12.6-7.4 24-18.9 29.2s-25 3.1-34.4-5.3L131.8 352H64c-35.3 0-64-28.7-64-64V224c0-35.3 28.7-64 64-64h67.8L266.7 40.1c9.4-8.4 22.9-10.4 34.4-5.3z"/></svg>
                                    <input class="volumeSlider" type="range" id="volumeSlider" min="0" max="1" step="0.01" value="0.5"/>                                    
                                </div>
                                <div class="subControls">                                        
                                    <input class="seekBar" type="range" id="seekBar" min="0" max="100" step="1" value="0"/>
                                </div>
                            </div>
                        </div>                    
                    
                    </div>
                    <a href="{% url 'text_to_mp3:download_audio' %}" title="Download" class="download" download>Download</a>
                </div>
            </div>
            {% comment %} Modal {% endcomment %}
        </div>
    </div>
{% endblock dynamic_content %}

templates/index.html
{% extends 'base.html' %} 

{% load static %}
{% block main_content %}

<div class="_segment">
  <div class="_segment_form_1">    
    <div class="text_input_form">
      <form>
        {% csrf_token %}
        <div class="last">
          <div class="container">
            <div class="header">
              <img src="{% static 'images/cancel.png' %}" alt="" class="clear" />
            </div>          
            {{ text_input_form.text_to_convert }}
          </div>
        </div>
        
        <span class="small-error-span error-span">
          <span class="error-span-main-wrap">
            <span class="material-icons-outlined"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#bb0000"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg></span>
            <p>Please fill in this field first</p>
          </span>
          <span class="material-icons-outlined cancel-alert-button-text"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#bb0000"><path d="M0 0h24v24H0V0z" fill="none" opacity=".87"/><path d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm3.59-13L12 10.59 8.41 7 7 8.41 10.59 12 7 15.59 8.41 17 12 13.41 15.59 17 17 15.59 13.41 12 17 8.41z"/></svg></span>
        </span>

        <div class="speak convert-entered-text-btn-div">
            <button class="convert-entered-text-btn" name="convert_entered_text" type="button" id="speak">Convert</button>
        </div>
      </form>
    </div>
  </div>
  <div class="alternative-text-wrapper">
    <hr />
    <p class="alternative-text">OR</p>
    <hr />
  </div>
  <!--Drag and drop files-->
  <div class="_segment_form_2">
    <div class="accepted-files">upload a TXT, DOCX or PDF file</div>
    <form class="form-container" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="upload-files-container">
        <div class="drag-file-area">
          <span class="material-icons-outlined upload-icon"> <svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="50px" viewBox="0 0 24 24" width="50px" fill="#FFFFFF"><g><rect fill="none" height="50" width="50"/></g><g><path d="M18,15v3H6v-3H4v3c0,1.1,0.9,2,2,2h12c1.1,0,2-0.9,2-2v-3H18z M7,9l1.41,1.41L11,7.83V16h2V7.83l2.59,2.58L17,9l-5-5L7,9z"/></g></svg> </span>
          <h3 class="dynamic-message">Drag & drop any file here</h3>
          <label class="label">
            or
            <span class="browse-files">
              {{ file_input_form.file_to_convert }}
              <span class="browse-files-text">browse file</span>
              <span>from device</span>
            </span>
          </label>
        </div>
        <span class="cannot-upload-message">
          <span class="material-icons-outlined"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#bb0000"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg></span>
          <span class="select-file-text"> Please select a file first </span>
          <span class="material-icons-outlined cancel-alert-button-file">
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#bb0000"><path d="M0 0h24v24H0V0z" fill="none" opacity=".87"/><path d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm3.59-13L12 10.59 8.41 7 7 8.41 10.59 12 7 15.59 8.41 17 12 13.41 15.59 17 17 15.59 13.41 12 17 8.41z"/></svg></span>
          </span>
        <div class="file-block">
          <div class="file-info">
            <span class="material-icons-outlined file-icon"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M8 16h8v2H8zm0-4h8v2H8zm6-10H6c-1.1 0-2 .9-2 2v16c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm4 18H6V4h7v5h5v11z"/></svg></span>
            <div class="file-name"> </div class="spearator">|<div class="file-size"> </div>
          </div>
          <div class="material-icons remove-file-icon"><svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#fff"><path d="M0 0h24v24H0z" fill="none"/><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/></svg></div>
        </div>

        <button type="button" class="upload-button">Upload</button>
      </div>
    </form>
  </div>

  <!--Drag and drop files-->
</div>

{% endblock main_content %}